# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# extract_by_masc.py
# Created on: 2014-01-29 10:52:50.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


# Local variables:
Output_raster = ""

# Process: Extract by Mask
arcpy.gp.ExtractByMask_sa("", "", Output_raster)

