# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# raster_calculator_v02.py
# Created on: 2014-01-29 19:21:18.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


# Local variables:
campos_patch_clump_mata_limpa_img_img = "campos_patch_clump_mata_limpa_img.img"
campos_patch_clump_mata_limpa_img_img__2_ = "campos_patch_clump_mata_limpa_img.img"
teste = "D:\\data\\john_pc2\\projeto_modelagem_canastra\\corredores_paisagem1\\teste"

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("Con(\"%campos_patch_clump_mata_limpa_img.img%\" == 0,-9999,\"%campos_patch_clump_mata_limpa_img.img%\")", teste)

