# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# raster_calculator.py
# Created on: 2014-01-29 18:44:27.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


# Local variables:
Output_raster = "C:\\Users\\semeadores\\Documents\\ArcGIS\\Default.gdb\\rastercalc"

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("", Output_raster)

